# Setup
title:        JCDE2016 Raspberry Pi workshop
tagline:      Documentation for JCDE2016 Raspberry Pi workshop
baseurl:      "http://andrefs.github.io/jcde2016-rpi"

# About/contact
author:
  name:       Luís Santos e André Santos
