# Setup
title:        jCDE 2016 - Workshop Raspberry Pi
tagline:      Documentação para o workshop
baseurl:      "http://andrefs.github.io/jcde2016-rpi"

# About/contact
author:
  name:       Luís Santos e André Santos
